version: '3'
services:
  api:
    build: journail_backend/journail_api
    ports:
      - "5056:5000"
    environment:
      - PYTHONPATH=/
      - FLASK_PORT=5000
      - SQLALCHEMY_DATABASE_URI=sqlite:////database/journail_prod.db
    volumes:
      - ./journail_backend/database:/database
  frontend:
    build: journail-frontend-ng
    volumes:
# docker run -it -v /Users/maelissteissier/JournailingApp/final_publish/journail/nginx_server/journail_frontend_build_from_docker:/journail_frontend_build_from_docker journail_frontend /bin/sh
      - ./nginx_server/journail_frontend_build_from_docker:/journail_frontend_build_from_docker/
  server:
    build: nginx_server
    ports:
      - "8086:8080"
    depends_on:
      - api