--INSERT INTO journal_category VALUES(1,1,'food');

INSERT INTO food_ref VALUES(1,100,30,'Caprice des dieux','gramme');
INSERT INTO food_ref VALUES(2,35,1,'Vache kiri','Triangle');
INSERT INTO food_ref VALUES(3,190,2,'Oeuf jumbo','Oeuf');
INSERT INTO food_ref VALUES(4,129,1,'Napolitain','Gateau');
INSERT INTO food_ref VALUES(5,250,50,'Chips marmite','gramme');
INSERT INTO food_ref VALUES(6,50,55,'Jambon paysan','gramme');
INSERT INTO food_ref VALUES(7,440,1,'Croissant Gianduja','1 croissant (100g)');
INSERT INTO food_ref VALUES(8,52,100,'Pomme','grammes');
INSERT INTO food_ref VALUES(9,110,30,'Oka champignons','grammes');
INSERT INTO food_ref VALUES(10,100,1,'Pain de mie Pom','Tranche');
INSERT INTO food_ref VALUES(11,80,30,'Kiri Tartinade','grammes');
INSERT INTO food_ref VALUES(12,90,4,'Craquelins Breton Herb and Garlic Glut.Free','craquelin');
INSERT INTO food_ref VALUES(13,90,4,'Craquelin Breton Herb&Garlic Glut.Free','craquelin');
INSERT INTO food_ref VALUES(14,90,30,'Rondelé noix de dordogne','grammes');
INSERT INTO food_ref VALUES(15,495,100,'Croutons français ail','');
INSERT INTO food_ref VALUES(16,250,45,'Granola maison','grammes');
INSERT INTO food_ref VALUES(17,160,175,'Yogourt Fraise Activia','grammes');
INSERT INTO food_ref VALUES(18,360,4,'Pancrepes du mix costco','crêpe');
INSERT INTO food_ref VALUES(19,360,100,'Fromage raclette','grammes');
INSERT INTO food_ref VALUES(20,100,19,'Nutella','grammes');
INSERT INTO food_ref VALUES(21,290,100,'Pain blanc baguette','grammes');
INSERT INTO food_ref VALUES(22,100,15,'Mayonnaise Maille','ml');
INSERT INTO food_ref VALUES(23,371,100,'Pain aux noix','grammes');
INSERT INTO food_ref VALUES(24,400,100,'Comté','grammes');
INSERT INTO food_ref VALUES(25,350,100,'Farine blanche','grammes');
INSERT INTO food_ref VALUES(26,165,100,'Poitrine poulet désossée','grammes');
INSERT INTO food_ref VALUES(27,3189,2526,'Dahl lentilles beluga','grammes');
INSERT INTO food_ref VALUES(28,180,2,'Madeleines','Madeleine');
INSERT INTO food_ref VALUES(29,120,125,'Compote pommes Andros','ml');
INSERT INTO food_ref VALUES(30,70,10,'Beurre','grammes');
INSERT INTO food_ref VALUES(31,1213,4,'Flatbread Olivier','Flatbread');
INSERT INTO food_ref VALUES(32,400,100,'Rillettes de porc','grammes');
INSERT INTO food_ref VALUES(33,39,100,'Pêche','grammes');
INSERT INTO food_ref VALUES(34,16,5,'Sucre blanc (ml)','ml');
INSERT INTO food_ref VALUES(35,90,100,'Banane','grammes');
INSERT INTO food_ref VALUES(36,81,100,'Patates vapeur','grammes');
INSERT INTO food_ref VALUES(37,2379,692,'Gâteau bananes yogourt fraise','grammes');
INSERT INTO food_ref VALUES(38,100,30,'Camembert','grammes');
INSERT INTO food_ref VALUES(39,270,115,'Saucisses vin blanc échalotte','grammes');
INSERT INTO food_ref VALUES(40,220,60,'Sirop d\''érable kirkland','ml');
INSERT INTO food_ref VALUES(41,64,25,'Pruneaux dénoyautés','grammes');
INSERT INTO food_ref VALUES(42,130,40,'Raisins secs dorés','grammes');
INSERT INTO food_ref VALUES(43,17,100,'Courgette','grammes');
INSERT INTO food_ref VALUES(44,30,1,'Cube bouillon','Cube');
INSERT INTO food_ref VALUES(45,41,100,'Carottes','grammes');
INSERT INTO food_ref VALUES(46,95,125,'Semoule couscous cuite (ml)','ml');
INSERT INTO food_ref VALUES(47,2568,1874,'Tajine pruneaux et saucisses','grammes');
INSERT INTO food_ref VALUES(48,646,403,'Semoule cuite president','grammes');
INSERT INTO food_ref VALUES(49,15,100,'Salade verte','grammes');
INSERT INTO food_ref VALUES(50,456,100,'Castello bleu extra creamy','gramme');
INSERT INTO food_ref VALUES(51,93,1,'Choco prince blé entier','biscuit');
INSERT INTO food_ref VALUES(52,160,85,'Frites drive-thru','grammes');
INSERT INTO food_ref VALUES(53,34,100,'Brocolis','grammes');
INSERT INTO food_ref VALUES(54,1750,763,'Pain maison','grammes');
INSERT INTO food_ref VALUES(55,150,100,'Pois chiche cuit','grammes');
INSERT INTO food_ref VALUES(56,70,30,'Baba gannouj','grammes');
INSERT INTO food_ref VALUES(57,70,30,'Hummus traditionnel fontaine santé','grammes');
INSERT INTO food_ref VALUES(58,40,15,'Hellmann light mayonnaise','ml');
INSERT INTO food_ref VALUES(59,110,30,'Cheddar fort','grammes');
INSERT INTO food_ref VALUES(60,724,485,'Hummus maison','grammes');
INSERT INTO food_ref VALUES(61,60,100,'Mangue','grammes');
INSERT INTO food_ref VALUES(62,120,100,'Riz basmati cuit','grammes');
INSERT INTO food_ref VALUES(63,80,100,'Raisin','grammes');
INSERT INTO food_ref VALUES(64,290,115,'Saucisses emmental cochonaille','grammes');
INSERT INTO food_ref VALUES(65,240,1,'Petite brioche au lait - Fournée dorée','brioche');
INSERT INTO food_ref VALUES(66,90,70,'Jambon blanc - chef george','grammes');
INSERT INTO food_ref VALUES(67,110,30,'Bleu Gorgonzola - Castello','grammes');
INSERT INTO food_ref VALUES(68,80,10,'Huile d''olive','ml');
INSERT INTO food_ref VALUES(69,120,175,'Yogourt nature activia','grammes');
INSERT INTO food_ref VALUES(70,200,43,'Petits poissons salés - Goldfish','grammes');
INSERT INTO food_ref VALUES(71,90,30,'Prosciutto','grammes');
INSERT INTO food_ref VALUES(72,60,1,'Ficello','1 batonnet');
INSERT INTO food_ref VALUES(73,42,1,'Tranche Bacon Cuite','Tranche');
INSERT INTO food_ref VALUES(74,110,1,'Brioche tranche','Tranche');
INSERT INTO food_ref VALUES(75,220,3,'Bebe croissants commerciaux','1 bébé croissant');
INSERT INTO food_ref VALUES(76,264,100,'Hellman light mayo - grams','grammes');
